### ISSUE TITLE
 error while loading shared libraries:

### ISSUE THREAD

**Issue by diorn** [Leonidas300/steamshortcutmaker#1]
Hi, getting this error when running the appimage on linux mint 20

`./ShortcutMaker-x86_64-Ubuntu.AppImage: error while loading shared libraries: __vdso_gettimeofday: invalid mode for dlopen(): Invalid argument`

**Comment by Leonidas300** [comment]
Hi, 
According to this thread on [StackOverflow](https://stackoverflow.com/questions/40932215/error-while-using-a-newer-version-of-glibc) your glibc must much to I think the ones I compiled so I have glibc 2.31 and used qt 5.14.2 On Ubuntu Version. Tell me wich one you download? Ubuntu or Zorin? and also please note I'm not Qt or Linux Master but I will try to help.

**Comment by diorn** [comment]
Thanks for your reply. I have downloaded the ubuntu version and it did not run, so i tried compiling it but still not working as per my other opened issue

LE:
In the meantime i have managed to get steam to run a lutris game just using this method for creating "add nonsteam game" shortcut:
Target: "/usr/games/lutris"
Start In: "/usr/games"
Launch option: lutris:rungame/identifier

This was not working before but apparently was due to a lutris bug which the latest build has fixed

**Comment by Leonidas300** [comment]
Yeah it didn't work for me also that's why I made this app. Well I comile it with most recent qt and os system at the time. I used linuxdeploy with --unsuported tag so as the description says it may not work on other systems. That's propably the reason. Anyway good to know that lutrix method is working for you now :-) But if you still want to try my app I wrote the solution in your other thread. I hope it works now.
